version: "3.8"
services:
  # Frontend
  pp-frontend:
    image: peerprep/frontend
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - QUESTIONS_API=http://pp-question:1234
      - USER_API=http://pp-user:1235
      - NEXT_PUBLIC_PAIRING_API=ws://pp-pairing-front:4000
    profiles:
      - frontend

  # Question service
  pp-question:
    image: peerprep/question
    build:
      context: ../../backend/services/question
      dockerfile: Dockerfile
    environment:
      - PORT=1234
      - MONGO_URI=mongodb+srv://peerprep:Dhl3ib6FRiaPbMVj@cluster0.famfy54.mongodb.net/?retryWrites=true&w=majority
    expose:
      - 1234
    ports:
      - 1234:1234
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: questions
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - dev-mongodb:/data/db

  # User service
  pp-user:
    image: peerprep/user
    build:
      context: ../../backend/services/user
      dockerfile: Dockerfile
    environment:
      - PORT=1235
      - POSTGRES_USER=peerprep
      - POSTGRES_PASSWORD=Y2NhNz['A[FT*-2[
      - PG_PORT=5432
      - POSTGRES_URI=34.87.4.15
    expose:
      - 1235
    ports:
      - 1235:1235
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: user
    volumes:
      # - dev-postgres:/var/lib/postgresql/data
      - ../../backend/services/user/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - 5432:5432

  # Pairing services
  rabbitmq:
    image: rabbitmq
    expose:
      - 5672
  pp-pairing-front:
    image: peerprep/pairing-front
    build:
      context: ../../backend/services/pairing/pairing-front
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT=4000
    ports:
      - 4000:4000
  pp-pairing-back:
    image: peerprep/pairing-back
    build:
      context: ../../backend/services/pairing/pairing-back
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - QUESTION_URL=http://pp-question:1234
      - MATCHMAKING_MAX_WAIT_SECONDS=100
# Names our volume
volumes:
  # dev-postgres:
  #driver: local
  dev-mongodb:
    driver: local
