version: "3.8"
services:
  rabbitmq:
    image: rabbitmq
    expose:
      - 5672
  pp-pairing-front:
    image: pp-pairing-front
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
    ports:
      - ${PP_PAIRING_PORT}:${PP_PAIRING_PORT}
    depends_on:
      - rabbitmq
# Names our volume
volumes:
  my-db:
