version: "3.8"
services:
  pp-pairing-front:
    image: pp-pairing-front
    restart: always
    env_file:
      - pp-pairing-front.env
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
    expose:
      - 5672
# Names our volume
volumes:
  my-db:
