version: "3.8"
services:
  # Frontend
  pp-frontend:
    image: peerprep/frontend
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_PAIRING_API=ws://localhost:4000
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - QUESTIONS_API=http://pp-question:1234
      - USER_API=http://pp-user:1235
      - NEXT_PUBLIC_PAIRING_API=ws://localhost:4000
      - COLLAB_API=http://pp-collab-service:8000
      - JUDGE0_URL=http://judge0-server:2358
    profiles:
      - frontend

  # Question service
  pp-question:
    image: peerprep/question
    build:
      context: ../../backend/services/question
      dockerfile: Dockerfile
    environment:
      - PORT=1234
      - MONGO_URI=mongodb://pp-question-mongodb:27017
      - USER_API=http://pp-user:1235
    expose:
      - 1234
    ports:
      - 1234:1234
    depends_on:
      - pp-question-mongodb
  pp-question-mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: questions
    expose:
      - 27017
    ports:
      - 27018:27017
    volumes:
      - dev-mongodb:/data/db
    restart: always

  # User service
  pp-user:
    image: peerprep/user
    build:
      context: ../../backend/services/user
      dockerfile: Dockerfile
    environment:
      - PORT=1235
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - PG_PORT=5432
      - POSTGRES_URI=postgres
    expose:
      - 1235
    ports:
      - 1235:1235
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: user
    volumes:
      # - dev-postgres:/var/lib/postgresql/data
      - ../../backend/services/user/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
  # Pairing services
  rabbitmq:
    image: rabbitmq
    expose:
      - 5672
  pp-pairing-front:
    image: peerprep/pairing-front
    build:
      context: ../../backend/services/pairing/pairing-front
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT=4000
    ports:
      - 4000:4000
    restart: always

  pp-pairing-back:
    image: peerprep/pairing-back
    build:
      context: ../../backend/services/pairing/pairing-back
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - QUESTION_URL=http://pp-question:1234
      - EDITOR_SERVICE_URL=http://pp-collab-service:8000
      - MATCHMAKING_MAX_WAIT_SECONDS=100
      - LOGGING_LEVEL=debug
  pp-collab-service:
    image: peerprep/collab-service
    build:
      context: ../../backend/services/collab
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 8888:8888
    expose:
      - 8000
      - 8888
    depends_on:
      - pp-collab-service-mongodb
    environment:
      - MONGO_URI=mongodb://pp-collab-service-mongodb:27017/pairs
      - WEBSOCKET_URL=ws://localhost
      - PORT=8000
      - WEBSOCKET_PORT=8888
      - JUDGE0_URL=http://judge0-server:2358

  pp-collab-service-mongodb:
    image: mongo
    expose:
      - 27017
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_DATABASE: pairs
    restart: always

  # judge0 containers
  judge0-server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - 2358:2358
    expose:
      - 2358
    privileged: true
    restart: always
    platform: linux/amd64
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    platform: linux/amd64
    depends_on:
      - judge0-db
      - judge0-redis
  judge0-db:
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - 5433
    command: -p 5433
    restart: always

  judge0-redis:
    image: redis:6.0
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0.conf
    expose:
      - 6379
    volumes:
      - redis-data:/data
    restart: always

# Names our volume
volumes:
  # dev-postgres:
  #driver: local
  dev-mongodb:
    driver: local
  postgres-data:
  redis-data:
