# Kubernetes (K8s) Deployment for local cluster
# Ensure that the local docker images have first been compiled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pp-web
  name: pp-web
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pp-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pp-web
    spec:
      containers:
      - image: peerprep
        imagePullPolicy: Never
        name: peerprep
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: pp-web
spec:
  selector:
    app: pp-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
