export enum WS_METHODS {
  OP, // To indicate I've handled this
  GET_TURN,
  GET_TURN_RESULT,
  SWITCH_LANG, //
  RUN_CODE, //
  RUN_CODE_RESULT,
  NEXT_QUESTION,
  NEXT_QUESTION_CONFIRM,
  EXIT,
  MESSAGE,
  TESTCASE_ADD,
  TESTCASE_DELETE,
  TESTCASE_EDIT,
  READY, //
};