version: "3"
services:
  mongodb:
    image: mongo
    container_name: questions-mongodb
    environment:
      MONGO_INITDB_DATABASE: questions
    ports:
      - 27017:27017

  question-service:
    build:
      context: .
    container_name: questions-service
    ports:
      - 3000:3000
    depends_on:
      - mongodb
