version: "3"
services:
  question-mongodb:
    image: mongo
    container_name: question-mongodb
    environment:
      MONGO_INITDB_DATABASE: questions
    expose:
      - 27017
    ports:
      - 27018:27017

  question-service:
    build:
      context: .
    container_name: question-service
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - question-mongodb
