version: "3"
services:
  mongodb:
    image: mongo
    container_name: question-mongodb
    environment:
      MONGO_INITDB_DATABASE: questions
    ports:
      - 27017:27017

  question-service:
    build:
      context: .
    container_name: question-service
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
