version: "3"
services:
  mongodb:
    image: mongo
    container_name: question-mongodb
    environment:
      MONGO_INITDB_DATABASE: questions
    ports:
      - 27017:27017

  postgres:
    image: postgres:latest
    container_name: question-image-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: images
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${PG_PORT}:5432"

  question-service:
    build:
      context: .
    container_name: question-service
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
      - postgres
