version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: pairs
  collab-service:
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
      - ${WEBSOCKET_PORT}:${WEBSOCKET_PORT}
    depends_on:
      - mongodb
