apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-question
spec:
  selector:
    matchLabels:
      app: peerprep-question
  template:
    metadata:
      labels:
        app: peerprep-question
    spec:
      containers:
        - name: peerprep-question
          image: asia-southeast1-docker.pkg.dev/ay2324s1-course-assessment-g28/ay2324s1-course-assessment-g28/peerprep-question:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: MONGO_URI
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peerprep-question
  name: peerprep-question
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 3000
  selector:
    app: peerprep-question
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: peerprep-question-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: peerprep-question
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
