apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pp-web
  name: pp-web
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pp-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pp-web
    spec:
      containers:
      - image: peerprep/frontend
        imagePullPolicy: Never
        name: peerprep-web
        # env:
        #   - name: NEXTAUTH_SECRET
        #     valueFrom:
        #       secretKeyRef:
        #         name: nextauth-secret
        #         key: NEXTAUTH_SECRET
        #   - name: GOOGLE_CLIENT_ID
        #     valueFrom:
        #       secretKeyRef:
        #         name: nextauth-secret
        #         key: GOOGLE_CLIENT_ID
        #   - name: GOOGLE_CLIENT_SECRET
        #     valueFrom:
        #       secretKeyRef:
        #         name: nextauth-secret
        #         key: GOOGLE_CLIENT_SECRET
        #   - name: QUESTIONS_API
        #     value: http://pp-question:1234
        #   - name: USER_API
        #     value: http://pp-user:1235
        #   - name: NEXT_PUBLIC_PAIRING_API
        resources: 
          limits:
            memory: "1024Mi"
            cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pp-web
  name: pp-web
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: pp-web
  sessionAffinity: None
  type: LoadBalancer

