# Judge0 Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-server
spec:
  selector:
    matchLabels:
      app: judge0-server
  template:
    metadata:
      labels:
        app: judge0-server
    spec:
      containers:
        - name: judge0-server
          image: judge0/judge0:1.13.0
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              value: "judge0"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: REDIS_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: POSTGRES_URI
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: judge0-server
  name: judge0-server
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 2358
      protocol: TCP
      targetPort: 2358
  selector:
    app: judge0-server
---
# Judge0 workers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-workers
spec:
  selector:
    matchLabels:
      app: judge0-workers
  template:
    metadata:
      labels:
        app: judge0-workers
    spec:
      containers:
        - name: judge0-workers
          image: judge0/judge0:1.13.0
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          command: ["./scripts/workers"]
          env:
            - name: POSTGRES_DB
              value: "judge0"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: REDIS_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: POSTGRES_URI
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: POSTGRES_PASSWORD
