apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-question
spec:
  selector:
    matchLabels:
      app: peerprep-question
  template:
    metadata:
      labels:
        app: peerprep-question
    spec:
      containers:
        - name: peerprep-question
          image: peerprep/question
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: MONGO_URI
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peerprep-question
  name: peerprep-question
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 3000
  selector:
    app: peerprep-question
  type: LoadBalancer
