apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-user
spec:
  selector:
    matchLabels:
      app: peerprep-user
  template:
    metadata:
      labels:
        app: peerprep-user
    spec:
      containers:
        - name: peerprep-user
          image: peerprep/user
          imagePullPolicy: Never
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: POSTGRES_URI
            - name: PG_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peerprep-user
  name: peerprep-user
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 1235
      protocol: TCP
      targetPort: 3000
  selector:
    app: peerprep-user
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: peerprep-user-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: peerprep-user
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
