apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-frontend
spec:
  selector:
    matchLabels:
      app: peerprep-frontend
  template:
    metadata:
      labels:
        app: peerprep-frontend
    spec:
      containers:
        - name: peerprep-frontend
          image: peerprep/frontend
          imagePullPolicy: Never
          resources:
            limits:
              memory: "2048Mi"
              cpu: "500m"
          env:
            - name: JUDGE0_URL
              value: "http://34.126.172.186:2358"
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: NEXTAUTH_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: QUESTIONS_API
              value: "http://peerprep-question.default.svc.cluster.local:1234"
            - name: USER_API
              value: "http://peerprep-user.default.svc.cluster.local:1235"
            - name: NEXT_PUBLIC_PAIRING_API
              value: "ws://localhost:4000"
            - name: COLLAB_API
              value: "http://peerprep-collab.default.svc.cluster.local:8000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peerprep-frontend
  name: peerprep-frontend
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: peerprep-frontend
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: peerprep-frontend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: peerprep-frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
